# Managed by eysenfalk/quickstart. Local changes will be replaced.
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
AuthenticationMethods publickey
GSSAPIAuthentication no
HostbasedAuthentication no
AuthorizedKeysFile .ssh/authorized_keys
AuthorizedKeysCommand none
TrustedUserCAKeys none
