name: checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  static:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: tests/static/run.sh

  ssh-container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:12-slim
          - debian:13-slim
          - ubuntu:22.04
          - ubuntu:24.04
          - ubuntu:26.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: tests/container/run.sh "${{ matrix.image }}"

  nix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: tests/nix/run.sh

  systemd-integration:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: tests/systemd/run.sh
